<body>
<div class="content">
  <div class="header">
    <div class="top_info">
      <div class="top_info_right">
        <p><b>You are not Logged in!</b> <a href="#">Log in</a> to check your messages.<br />
          Do you want to <a href="#">Log in</a> or <a href="#">register</a>?</p>
      </div>
      <div class="top_info_left">
        <p><b>28. March, 2006</b> - Tuesday<br />
          Check todays <a href="#">hot topics</a> or <a href="#">new products</a></p>
      </div>
    </div>
    <div class="logo">
      <h1><a href="#"><span class="dark">ABC &nbsp;</span>Services</a></h1>
    </div>
  </div>
  <div class="bar">
  <table align="right" width="80%" border="0">
  <tr>
  <td align="center" valign="top"><a href="Customers.php"><i class="fa fa-male" style="font-size:48px;color:gray"></i><br />Customer</a></td>
   <td align="center" valign="top"><i class="fa fa-ticket" style="font-size:48px;color:gray"></i><br />Tickets</a></td>
   <td align="center" valign="top"><i class="fa fa-navicon" style="font-size:48px;color:gray"></i><br />Estimate</a></td>
   <td align="center" valign="top"><i class="fa fa-wrench" style="font-size:48px;color:gray"></i><br />Parts</a></td>
    <td align="center" valign="top"><i class="fa fa-server" style="font-size:48px;color:gray"></i><br />Inventory</a></td>
	 <td align="center" valign="top"><i class="fa fa-cart-plus" style="font-size:48px;color:gray"></i><br />Invoice</td>
	  <td align="center" valign="top"><i class="fa fa-bar-chart" style="font-size:48px;color:gray"></i><br />Reports</a></td>
	   <td align="center" valign="top"><a href="#" accesskey="r"><i class="fa fa-cog" style="font-size:48px;color:gray"></i><br />Admin</a></td>
  </tr>
  <tr>
  <td align="center" colspan="8"><i class="fa fa-ticket" style="font-size:48px;color:gray"></i><br />&nbsp;</a></td>
  </tr>
  </table>
   
  </div>
  <div class="search_field">
    <form method="post" action="#">
      <div class="search_form">
        <p>Search the Web:
          <input type="text" name="search" class="search" />
          <input type="submit" value="Search" class="submit" />
          <a class="grey" href="#">Advanced</a></p>
      </div>
    </form>