<body>
<div class="content">
  <div class="header">
    <div class="top_info">
      <div class="top_info_right">
        <p><b>You are not Logged in!</b> <a href="#">Log in</a> to check your messages.<br />
          
      </div>
      <div class="top_info_left">
        
      </div>
    </div>
    <div class="logo">
      <h1 align="left"><a href="#"><span class="dark">ABC &nbsp;</span>Services</a></h1>
    </div>
  </div>
  <div class="bar">
  <table align="right" width="80%" border="0">
  <tr>
  <td align="center"></td>
   <td align="center"></td>
   <td align="center"></td>
   <td align="center"></td>
    <td align="center"></td>
	 <td align="center"></td>
	  <td align="center"></td>
	   <td align="center"></td>
  </tr>
  </table>
   
  </div>
  <div class="search_field">
      <div class="search_form">
        
      </div>
    </form>